### ISSUE TITLE
The repository is no longer signed

### ISSUE THREAD

**Issue by YaserAmini88** [entercloudsuite/ansible-haproxy#12]
Hi
I ran the playbook against an ubnutu server and I got the error below :

fatal: [ansible@93.115.150.236]: FAILED! => {"changed": false, "msg": "E:Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 143.204.101.42 443], E:The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is no longer signed."}

Could you please help me to resolve this issue ?

**Comment by jsecchiero** [comment]
This role doesn't install any docker repo. You must check official docker guide to use the correct gpg keys https://docs.docker.com/install/linux/docker-ce/ubuntu/.
